                                Task4
                                

#1. Introduction to NumPy:
                       NumPy (Numerical Python) is the fundamental package for numerical computation in
Python.It is the most popular machine learning library in Python.NumPy is a Python library used for working with arrays. It also has functions for working in domain of linear algebra, fourier transform, and
matrices. It is an open source library. NumPy is one of the fundamental packages for Python providing support for large multidimensional arrays and matrices. NumPy relies on BLAS and LAPACK for efficient linear algebra computations. NumPy can also be used as an efficient multi-dimensional container of generic data.
                         NumPy is one of the most used libraries for tasks involving modern scientific
computations and evolving yet powerful domains like Data Science and Machine Learning. It supports for powerful N-dimensional array objects and built-in tools for performing intensive mathematical as well as scientific calculations. It is used for delivering high performance, interoperability with various computing platforms and hardware, and ease of use.

#2.Array in numpy
    ndarray:  ndarray is a short form for N-dimensional array which is a important component of NumPy.
It’s allows us to store and manipulate large amounts of data efficiently. All elements in an ndarray must 
be of same type making it a homogeneous array. This structure supports  multiple dimensions which makes
it ideal for handling complex datasets like those used in scientific computing or data analysis. 
With this we can perform fast and memory efficient operations on data.

In [14]:
#creating  arrays using

In [39]:

import numpy as np

a=np.array([1,2,3,4])
print(a)
#2d and 3d array
b=np.array([[1,2,3],[4,5,6]])
print(b)
#3d array
c=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)


[1 2 3 4]
[[1 2 3]
 [4 5 6]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [10]:
#np.zeros()
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
#np.ones()
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
#np.arange()
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
#np.linspace
np.linspace(-10,10,10)


array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [17]:
#Array indexing and slicing.


In [16]:

a1=np.arange(10)
a2=np.arange(12).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
a2[0,:]

array([0, 1, 2, 3])

In [19]:
a2[::2,1::2]


array([[ 1,  3],
       [ 9, 11]])

In [20]:
a3[::2]

array([[[0, 1],
        [2, 3]]])

In [22]:
a3[::2]

array([[[0, 1],
        [2, 3]]])

In [23]:
#3. Array Operations

In [26]:
# Arithmetic operations

a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [27]:
#addition
a1+a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [28]:
#subtration
a2-a1

array([[12, 12, 12, 12],
       [12, 12, 12, 12],
       [12, 12, 12, 12]])

In [30]:
#multiplication
a1*a2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [31]:
#division
a1/a2

array([[0.        , 0.07692308, 0.14285714, 0.2       ],
       [0.25      , 0.29411765, 0.33333333, 0.36842105],
       [0.4       , 0.42857143, 0.45454545, 0.47826087]])

In [32]:
#Element-wise operations and functions

In [33]:
#np.sqrt
np.sqrt(a1)

array([[0.        , 1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974, 2.64575131],
       [2.82842712, 3.        , 3.16227766, 3.31662479]])

In [34]:
#np.exp()
np.exp(a1)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

In [36]:
#np.sin()
np.sin(a1)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849, -0.54402111, -0.99999021]])

In [38]:
#4.Array Shapes and Reshaping
a = np.array([[1, 2], [3, 4], [5, 6]])

print(a.shape)         # (3, 2)
print(a.ndim)          # 2

print(a.reshape(2, 3))
print(a.flatten())
print(a.T)             # Transpose

# Concatenation and splitting
b = np.array([[7, 8], [9, 10], [11, 12]])
print(np.concatenate((a,b),axis=1))

(3, 2)
2
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[[1 3 5]
 [2 4 6]]
[[ 1  2  7  8]
 [ 3  4  9 10]
 [ 5  6 11 12]]


In [44]:
#Array Manipulation
#Indexing and slicing:understanding multdimensional arrays
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
# Slicing rows
row_1 = matrix[0, :]  
print(row_1)  

# Slicing columns
col_2 = matrix[:,0]
print(col_2)

[1 2 3]
[1 4 7]


In [45]:
#Masking
a = np.array([10, 20, 30, 40])
mask = a > 20
print(a[mask]) 

[30 40]


In [46]:
#fancy indexing
idx = [0, 2]
print(a[idx])  

[10 30]


In [47]:
#6.Mathematical Functions


In [49]:
#Universal Function
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

print(np.add(x, y))
print(np.subtract(x,y))
print(np.multiply(x,y))


[5 7 9]
[-3 -3 -3]
[ 4 10 18]


In [50]:
#Statistical Functions
p=np.array([4,7,9,34,51,67,90,95])
print(np.mean(p))
print(np.median(p))
print(np.std(p))
print(np.var(p))
print(np.min(p))
print(np.max(p))



44.625
42.5
34.61552216853012
1198.234375
4
95


In [53]:
#Linear algebra Function
A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 0], [1, 2]])

print(np.dot(A, B))       
print(np.linalg.inv(A))
print(np.matmul(A,B))
print(np.linalg.eig(A))

[[ 4  4]
 [10  8]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[ 4  4]
 [10  8]]
EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))


In [54]:
#7. Random Number Generation

np.random.seed(42)

print(np.random.rand(2, 2))        
print(np.random.randint(1, 10, 5)) 

arr = np.array([1, 2, 3, 4, 5])
np.random.shuffle(arr)
print(arr)

print(np.random.permutation(arr))


[[0.37454012 0.95071431]
 [0.73199394 0.59865848]]
[7 3 7 8 5]
[1 2 3 5 4]
[1 3 5 2 4]


8. Broadcasting:    
                   Broadcasting in NumPy allows us to perform arithmetic operations on arrays of different shapes without reshaping them. It automatically adjusts the smaller array to match the larger array's shape by replicating its values along the necessary dimensions. 





In [55]:
array_2d = np.array([[1, 2, 3], [4, 5, 6]])  
scalar = 10  

result = array_2d + scalar
print(result)

[[11 12 13]
 [14 15 16]]


#Rules of broadcasting:
1. Dimension Alignment:
NumPy starts by comparing the shapes of arrays from the trailing (rightmost) dimension and works its way left. 
2. Compatibility Check:
Two dimensions are compatible if they are equal in size or if one of them has size 1. 
3. Stretching/Replication:
If a dimension has size 1, the array is stretched along that axis to match the other array's size. 
4. Rank Adjustment:
If arrays have different numbers of dimensions (ranks), NumPy adds "wrapper dimensions" with size 1 to the smaller array until the ranks match. 
5. Error Handling:
If dimensions cannot be aligned using these rules, a ValueError is raised. 